### ISSUE TITLE
Version 2.1 vs. version code 0200

### ISSUE THREAD

**Issue by oetiker** [peiTeX/qrbill#3]
https://github.com/peiTeX/qrbill/blob/bf0d606bc06515b3d06abba671b0f56859050658/qrbill.dtx#L987

https://github.com/peiTeX/qrbill/blob/bf0d606bc06515b3d06abba671b0f56859050658/qrbill.dtx#L292

**Comment by TeXhackse** [comment]
Thanks for the Report. 
We checked the documentation once again and discussed this. The code `0200` is only found in the example data. In the guideline 2.1 is written that it will replace version 2.0. And explicitly that `0200` is the code for version 2.0. That's why we insist on `0210` to be correct. The QR-code has also been checked to be valid using the six validator.

We already contacted six before the first release about some other issues and inconsistencies but did not receive any answer. So from our point of view, this is only another one…

Did you find any piece of information concerning this inconsistency?
So is there any published material, where I can find that Version 2.1 will still use 0200? 
If you found any, I'd be thankful for a hint.

I'll leave the issue open and am waiting for you to reply on that question.

**Comment by oetiker** [comment]
well the validator is happy yes, but if you try to pay a qrbill with 0210 at least with the postfinance app it gets refused as invalid ... changing the version to 0200 makes it work. That is why I opened the bug report.

**Comment by TeXhackse** [comment]
Okay. Well the 0210 is not hardcoded for our setup. The user can change this. So if one wants to support 0200 it is possible and not a but at all. We're just using 2.1 in the example, because it's the current version of the standard. 

I will think about adding a note about this. But the issue might still not be qrbill but the postfinance app, because the version 2.1 replaced 2.0 already in September 2019… And I am afraid there will be or already are some banking apps which don't support 2.0 anymore…

**Comment by oetiker** [comment]
I did a little field research, looking at other libraries for qrbills in java php and python ... they boldly claim to support 2.1 standard and then internally *hardcode* to the version to 0200 ... 

In any event, I have been sending out qr bills generated with your cool implementation (after setting version to 0200) for a few days now and have not yet heard any complaints from the recipients ... thank you very much for making this available!

**Comment by TeXhackse** [comment]
Thank you. I just did the same and am really confused.  Especially since it's valid, according to six. 

I'll add information on the discussion to the sources and will do the release today. But I'll also contact six once more. Because this is really confusing.

(And hardcoding a version number should never be a good idea …But probably the banking apps did the same …)

And I am really glad to hear, you like our package :)

**Comment by oetiker** [comment]
The whole qrbill thing is a disaster when looking at the way it is defined ... it seems like a very clear 'design by committee' problem. At least they managed to switch to utf-8 for encoding in version 2 ... but then still restricting the char set to latin 1 ... :see_no_evil:

**Comment by oetiker** [comment]
This morning I received the first payments made on the qrbills I sent out ... so it does really work ..

**Comment by TeXhackse** [comment]
I am creally confused now. six canged there validator and now the 0210 codes are not accepted anymore. Probably because they realized that everyone only used 0200 …

**Comment by TeXhackse** [comment]
I just found an update concerning this. They changed the standard, they will clain this is no technical change but now the standard itself says that all Version 2.x should use 0200 as version code.

> Achtung: SIX hat in Zusammenarbeit mit Vertretern des Finanzplatzes entschieden, dass  in der Masterversion 02 nur die Versionsangabe '0200' zugelassen ist. Ab Masterversion 03 wird die Abbildung von Unterversionen ermöglicht.

See https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-de.pdf

**Comment by oetiker** [comment]
yey ... this is so much fun :) just imagine how great it would be if this standard had been created by people who had a clue ... lets say maybe using json as an encoding ...

**Comment by viktoriasee** [comment]
I can confirm that the Migros Bank app for Android only accepts 0200 version code as of version 8.6.2708.

So I suggest to change the default value in `swiss.qrbill-cfg.tex` to `0200`.

**Comment by TeXhackse** [comment]
This issue concerns version 2.1 it will be obsolete with the version 2.2. Update is in preperation, which will resolve this. Changing the version number is against the standard version 2.1 

The implementation of 0200 was a misstake but since most people did it was decided to keep that. This information was not documented until Version 2.2. was released.

**Comment by TeXhackse** [comment]
I just uploaded the new release to CTAN, as soon as it's installed I will also release via GitHub. This issue is closed since it became obsolete with version 2.2 of the standard.

The Information will stay in the documentation, because even with version 2.1 it was not our fault.
